# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"<\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"(\n\x0cUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xf5\x01\n\x0bUserService\x12\x39\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\x12\x33\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x12.user.UserResponse\x12\x39\n\nUpdateUser\x12\x17.user.UpdateUserRequest\x1a\x12.user.UserResponse\x12;\n\nDeleteUser\x12\x17.user.DeleteUserRequest\x1a\x14.user.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=20
  _globals['_USER']._serialized_end=67
  _globals['_CREATEUSERREQUEST']._serialized_start=69
  _globals['_CREATEUSERREQUEST']._serialized_end=117
  _globals['_GETUSERREQUEST']._serialized_start=119
  _globals['_GETUSERREQUEST']._serialized_end=147
  _globals['_UPDATEUSERREQUEST']._serialized_start=149
  _globals['_UPDATEUSERREQUEST']._serialized_end=209
  _globals['_DELETEUSERREQUEST']._serialized_start=211
  _globals['_DELETEUSERREQUEST']._serialized_end=242
  _globals['_USERRESPONSE']._serialized_start=244
  _globals['_USERRESPONSE']._serialized_end=284
  _globals['_DELETERESPONSE']._serialized_start=286
  _globals['_DELETERESPONSE']._serialized_end=319
  _globals['_USERSERVICE']._serialized_start=322
  _globals['_USERSERVICE']._serialized_end=567
# @@protoc_insertion_point(module_scope)
